/** Render a Report as Markdown (for PR comments / CI artifacts). */

import { CATEGORY_LABELS, type Report } from "../types.js";

const ICON = { error: "✗", warning: "⚠", info: "ℹ", pass: "✓" } as const;

export function toMarkdown(report: Report): string {
  const s = report.summary;
  const out: string[] = [];
  out.push(`# cookie-doctor report`);
  out.push("");
  out.push(
    `**${s.score}/100 (${s.grade})** across **${s.cookies}** cookie(s) — ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info(s)`,
  );
  out.push("");

  for (const c of report.cookies) {
    out.push(`## \`${c.name}\` — ${c.score}/100 (${c.grade}) _(${c.source})_`);
    out.push("");
    if (c.findings.length === 0) {
      out.push(`✓ No issues found.`);
      out.push("");
      continue;
    }
    out.push(`| | Category | Attribute | Issue | Fix |`);
    out.push(`| - | -------- | --------- | ----- | --- |`);
    for (const f of c.findings) {
      const fix = (f.fix ?? "").split("\n")[0]!.replace(/\|/g, "\\|");
      out.push(
        `| ${ICON[f.severity]} | ${CATEGORY_LABELS[f.category]} | \`${f.attribute ?? "—"}\` | ${f.title.replace(/\|/g, "\\|")} | ${fix} |`,
      );
    }
    out.push("");
  }

  out.push(`---`);
  out.push(`<sub>Generated by cookie-doctor v${report.version} · ${report.generatedAt}</sub>`);
  out.push("");
  return out.join("\n");
}
